//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omegashipping.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string BookingRefNo { get; set; }
        public string ShipperName { get; set; }
        public Nullable<int> PlaceOfBooking { get; set; }
        public string Consignee { get; set; }
        public string DateOfStacking { get; set; }
        public Nullable<int> PlaceOfRec { get; set; }
        public Nullable<int> POD { get; set; }
        public Nullable<int> Voyage { get; set; }
        public Nullable<int> Vessel { get; set; }
        public string VesselOperator { get; set; }
        public Nullable<int> PreCarriage { get; set; }
        public Nullable<int> DestCarriage { get; set; }
        public Nullable<int> TypeOfCargo { get; set; }
        public Nullable<int> Container { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Commodity { get; set; }
        public Nullable<int> GrWt { get; set; }
        public string DateOfBooking { get; set; }
        public int CustomerID1 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
