//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omegashipping.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Track { get; set; }
    }
}
