//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omegashipping.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public int ID { get; set; }
        public string TypeofNumber { get; set; }
        public string SeqNo { get; set; }
        public int BookingconfigID { get; set; }
    
        public virtual Bookingconfig Bookingconfig { get; set; }
    }
}
