//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omegashipping.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Pid { get; set; }
        public string Pname { get; set; }
        public string Pdescription { get; set; }
        public Nullable<int> Prate { get; set; }
        public Nullable<int> PQuantity { get; set; }
    }
}
